apiVersion: v1
kind: Pod
metadata:
  name: affi
spec:
  containers:
  - name: aff
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values: 
            - helloworld-nginx
        topologyKey: "kubernetes.io/hostname"
