apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulsetpv2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/reddy
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
