apiVersion: v1
kind: Pod
metadata:
  name: podquota
spec:
  containers:
  - name: ex
    image: busybox
    command: ['sh','sleep','3000']
    resources:    
      requests:
        cpu: 1
      limits: 
        cpu: 5
