apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: test4pvc
spec:
  accessModes: 
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5G
  storageClassName: test4sc
