apiVersion: v1
kind: Pod
metadata:
  name: test3pod
spec:
  containers:
  - name: testc
    image: nginx
    ports:
    -  containerPort: 80
    volumeMounts:
    - name: testvol
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: testvol
    persistentVolumeClaim:
      claimName: test3pvc
