apiVersion: v1
kind: PersistentVolume
metadata: 
  name: test4pv
spec:
  accessModes: 
  - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 5G
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test4pvc
  storageClassName: test4sc
  gcePersistentDisk:
    fsType: "ext4"
    pdName: my-data-disk
