apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: john
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1lqQ0NBVW9DQVFBd0hURU5NQXNHQTFVRUF3d0VhbTlvYmpFTU1Bb0dBMVVFQ2d3RFlYQndNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyaWltQXJ3V3NLSk5tTll2S2crbU9pbVFtOGpQClcxamtFSWVUTS9CY0pmSG9BYWVJMjdWTncvelNMUTdickx2NGxxSThCOTRWR3hqZ09MQnNWRnc3NC9Vbkx2TGoKSnMyOGRSa1lNRGhNOE9ndHFkU3JNbjJERnlucFpZTHlJVVBJdXNIbzRpM0JacTkrc2dWdU8xbjNVbDAyNFdkcQpPaytUbnh6Zkd4QlpMc1B1RUpVR2h1aTdidXI1b2JjWEEzb2JjMGszMUhMYzRnTUtQQU10WDJhN2VVaWRreENqCk1wNWROc0FXbVROeFk2L2hQQzRGSU9GaW41azdoSXJqQ2xhZ0dGbEZSOU84cXFaS0J4bFZETStzcUFsSTNnby8KZGh1Qm5lanFDUVp3OENBVFRIelRGRk04QVJzMWcrREx2ZmhGSzErdTIzZ1djR3E0em5jMVFsK0ord0lEQVFBQgpvQUF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdRSnFmRGNuZDZRYWxjYU55RGtLWmE0NHFCS2NpU1N3dHFmCktQWTdXQ3NXblVNUGhMR2Q3bGNCSEdIdENXcWJFcTUrQkxPZDBoMFNXQXhOTHpydFhGc2M3NnhGQkRra1VCL28KVDhSZTRHalg1YWplRDB1dGVFTE9hN0hkOHUwaHNRdzBUNHZZd0sxQ241NTM3QXNlYW04WVJTSFNVbExZRFNPYgpXdGZkOGxhZ2Q1MkZxd253TmkwWWVFcXlzeEdHaW5qMVZKdlFwdS9YVlVLbXdwTFk1NFhpbEdZN1F2Z084QWVWCkJuVlI4Q2R4Y3dTK256MldVQytkVGhEMVVvaDh6bUt4aHcxUFZLQkoyOGRaY1E1RlRqMW4raDl5QS9veHFXOVAKY3ZhUWVkT2VlS1VBb1lvMXkzZ1hXL0oxT3U5NGd1YXE1aWJONDVQMnF5OWR5YVpjQmJzPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
