apiVersion: v1
kind: Pod
metadata:
  name: configdemo3
spec:
  containers:
  - name: alp3
    image: alpine
    command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
    env:
    - name: PLAYER
      valueFrom:
        configMapKeyRef:
          name: config
          key: initial_lives
    - name: HEY
      valueFrom:
        configMapKeyRef:
          name: envconf
          key: abc
    volumeMounts:
    - name: confi
      mountPath: /reddy
    volumeMounts:
    - name: confi2
      mountPath: /reddy2
  volumes:
  - name: confi
    configMap:
      name: config
      items:
      - key: "game.properties"
        path: "game.properties1"
  - name: confi2
    configMap:
      name: envconf
     
